import { defineDevice } from './defineDevice';
import type { DeviceDefinition } from '../deviceSchema';

/**
 * Passive rail hardware: patch panels, blank and brush panels. Every
 * keystone opening is a real addressable connector location — future
 * cables terminate on the same stable refs as switch ports.
 */
export const GENERIC_DEVICES: DeviceDefinition[] = [
  defineDevice({
    id: 'gen-patch-24',
    slug: 'patch-panel-24',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '24-Port Keystone Panel',
    modelNumber: 'PP-24K',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 40,
    weightKg: 0.9,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      '1U feed-through keystone panel — 24 pass-through jacks with an RJ45 opening on both faces (patch at the front, permanent cabling at the rear), plus a rear cable-support bar.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone',
        type: 'keystone',
        count: 24,
        label: 'Front 1–24',
        positionMm: [-205.8, 0, 20],
        pitchMm: 17.9,
      },
      // Rear of the same pass-through jacks: an RJ45 opening at the back
      // of each keystone body, so permanent/building cabling terminates
      // here exactly as on a real feed-through panel. Aligned to the
      // front openings; cables exit straight out the back.
      {
        id: 'keystone-rear',
        type: 'keystone',
        count: 24,
        label: 'Rear 1–24',
        location: 'rear',
        positionMm: [-205.8, 0, -7],
        pitchMm: 17.9,
      },
    ],
    // Silver brushed-metal finish so it colour-matches Ubiquiti Pro gear
    // (Dream Machine Pro, Pro Max) it typically shares a rack with.
    presentation: {
      faceplate: 'network',
      tone: 'metal',
      portsLabel: '24 openings',
      styleKey: 'ubiquiti',
    },
  }),
  defineDevice({
    id: 'gen-patch-48',
    slug: 'patch-panel-48',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '48-Port Keystone Panel',
    modelNumber: 'PP-48K',
    category: 'accessories',
    rackUnits: 2,
    depthMm: 40,
    weightKg: 1.7,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      '2U feed-through keystone panel — 48 pass-through jacks in two rows, each with an RJ45 opening on both faces (patch at the front, permanent cabling at the rear), plus a rear cable-support bar.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone-a',
        type: 'keystone',
        count: 24,
        label: 'Front 1–24',
        positionMm: [-205.8, 21, 20],
        pitchMm: 17.9,
        row: 0,
      },
      {
        id: 'keystone-b',
        type: 'keystone',
        count: 24,
        label: 'Front 25–48',
        positionMm: [-205.8, -21, 20],
        pitchMm: 17.9,
        row: 1,
      },
      // Rear RJ45 openings on the back of the same pass-through jacks.
      {
        id: 'keystone-a-rear',
        type: 'keystone',
        count: 24,
        label: 'Rear 1–24',
        location: 'rear',
        positionMm: [-205.8, 21, -7],
        pitchMm: 17.9,
        row: 0,
      },
      {
        id: 'keystone-b-rear',
        type: 'keystone',
        count: 24,
        label: 'Rear 25–48',
        location: 'rear',
        positionMm: [-205.8, -21, -7],
        pitchMm: 17.9,
        row: 1,
      },
    ],
    presentation: { faceplate: 'network', tone: 'dark', portsLabel: '48 openings' },
  }),
  defineDevice({
    id: 'gen-blank-1u',
    slug: 'blank-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Blank Panel',
    modelNumber: 'BP-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 15,
    weightKg: 0.3,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Solid filler panel for unused rack units.',
    tags: ['blank', 'passive'],
    accessoryKind: 'blank-panel',
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-brush-1u',
    slug: 'brush-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Brush Panel',
    modelNumber: 'BR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 25,
    weightKg: 0.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Cable pass-through panel with a full-width brush strip.',
    tags: ['brush', 'cable-management', 'passive'],
    accessoryKind: 'brush-panel',
    cableManagement: {
      kind: 'brush-panel',
      capacity: 48,
      costFactor: 0.8,
      nodes: [
        // Cables pass front↔rear through the brush strip.
        { id: 'brush-l', positionMm: [-110, 0, 0], axisMm: [0, 0, 1] },
        { id: 'brush-c', positionMm: [0, 0, 0], axisMm: [0, 0, 1] },
        { id: 'brush-r', positionMm: [110, 0, 0], axisMm: [0, 0, 1] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-mgmt-1u',
    slug: 'cable-manager-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Horizontal Cable Manager',
    modelNumber: 'CM-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 70,
    weightKg: 0.7,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Open finger-style horizontal manager: patch cables sweep in from either side and dress across the front.',
    tags: ['cable-management', 'horizontal', 'finger', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'horizontal-manager',
      capacity: 24,
      costFactor: 0.6,
      nodes: [
        { id: 'run-l', positionMm: [-140, 0, 80], axisMm: [1, 0, 0] },
        { id: 'run-c', positionMm: [0, 0, 80], axisMm: [1, 0, 0] },
        { id: 'run-r', positionMm: [140, 0, 80], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-finger-duct-2u',
    slug: 'finger-duct-2u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '2U Finger Duct',
    modelNumber: 'FD-2U',
    category: 'accessories',
    rackUnits: 2,
    depthMm: 90,
    weightKg: 1.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'High-density covered finger duct for heavy patch fields; cables enter between the fingers and run enclosed.',
    tags: ['cable-management', 'finger-duct', 'horizontal', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'finger-duct',
      capacity: 48,
      costFactor: 0.5,
      enclosed: true,
      nodes: [
        { id: 'duct-l', positionMm: [-140, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
        { id: 'duct-c', positionMm: [0, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
        { id: 'duct-r', positionMm: [140, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-ring-1u',
    slug: 'cable-ring-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U D-Ring Guide',
    modelNumber: 'DR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 55,
    weightKg: 0.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Two steel D-rings for light patch-cable dressing.',
    tags: ['cable-management', 'ring', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'cable-ring',
      capacity: 12,
      costFactor: 0.85,
      nodes: [
        { id: 'ring-l', positionMm: [-110, 0, 70], axisMm: [1, 0, 0], capacity: 6 },
        { id: 'ring-r', positionMm: [110, 0, 70], axisMm: [1, 0, 0], capacity: 6 },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-vertical-mgmt-4u',
    slug: 'vertical-manager-4u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '4U Vertical Manager',
    modelNumber: 'VM-4U',
    category: 'accessories',
    rackUnits: 4,
    widthMm: 80,
    depthMm: 90,
    weightKg: 1.8,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Vertical finger spine beside the right rail: reserves its span and carries vertical runs between patch fields.',
    tags: ['cable-management', 'vertical', 'finger', 'passive'],
    accessoryKind: 'cable-manager',
    mountingOffsetMm: 262,
    cableManagement: {
      kind: 'vertical-manager',
      capacity: 48,
      costFactor: 0.55,
      nodes: [
        { id: 'v-top', positionMm: [0, 66, 80], axisMm: [0, 1, 0] },
        { id: 'v-mid', positionMm: [0, 0, 80], axisMm: [0, 1, 0] },
        { id: 'v-bottom', positionMm: [0, -66, 80], axisMm: [0, 1, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-tray-1u',
    slug: 'cable-tray-rear-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Rear Cable Tray',
    modelNumber: 'CT-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 250,
    weightKg: 1.1,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Rear-mounted lattice tray carrying trunk runs across the back of the rack.',
    tags: ['cable-management', 'tray', 'rear', 'passive'],
    accessoryKind: 'cable-manager',
    defaultFacing: 'rear',
    cableManagement: {
      kind: 'cable-tray',
      capacity: 36,
      costFactor: 0.65,
      nodes: [
        { id: 'tray-l', positionMm: [-140, 0, -140], axisMm: [1, 0, 0] },
        { id: 'tray-c', positionMm: [0, 0, -140], axisMm: [1, 0, 0] },
        { id: 'tray-r', positionMm: [140, 0, -140], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'metal' },
  }),
  defineDevice({
    id: 'gen-power-raceway-1u',
    slug: 'power-raceway-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Power Raceway',
    modelNumber: 'PR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 250,
    weightKg: 1.2,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Dedicated rear raceway for power cords — keeps mains separated from data runs.',
    tags: ['cable-management', 'raceway', 'power', 'rear', 'passive'],
    accessoryKind: 'cable-manager',
    defaultFacing: 'rear',
    cableManagement: {
      kind: 'raceway',
      capacity: 16,
      costFactor: 0.6,
      enclosed: true,
      preferredFamilies: ['power'],
      nodes: [
        { id: 'race-l', positionMm: [-140, 0, -150], axisMm: [1, 0, 0] },
        { id: 'race-r', positionMm: [140, 0, -150], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-patch-guide-1u',
    slug: 'patch-guide-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Patch Cable Guide',
    modelNumber: 'PG-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 45,
    weightKg: 0.5,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Low-profile guide bar placed directly under a patch panel for short, tidy patch runs.',
    tags: ['cable-management', 'patch', 'guide', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'patch-guide',
      capacity: 24,
      costFactor: 0.7,
      preferredFamilies: ['copper', 'fiber'],
      nodes: [
        { id: 'guide-c', positionMm: [0, 0, 65], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-modem',
    slug: 'cable-modem',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: 'Cable Modem',
    modelNumber: 'CM-2500',
    category: 'routing',
    rackUnits: 1,
    widthMm: 160,
    heightMm: 42,
    depthMm: 140,
    mountingStandard: 'none',
    weightKg: 0.45,
    powerConsumptionWatts: 8,
    maximumPowerWatts: 12,
    description:
      'DOCSIS 3.1 cable modem with a 2.5GbE LAN port. Desktop form factor for shelf mounting where the coax drop enters the rack.',
    tags: ['modem', 'docsis', 'desktop', 'wan'],
    ports: [
      {
        id: 'lan',
        type: 'rj45',
        count: 1,
        label: 'LAN 2.5G',
        location: 'front',
        positionMm: [-35, 0, 70],
        speedGbps: 2.5,
        etherlighting: true,
      },
      {
        id: 'coax',
        type: 'other',
        count: 1,
        label: 'Coax',
        location: 'front',
        positionMm: [10, 0, 70],
      },
    ],
    power: {
      connectors: [
        { id: 'dc', type: 'dc', count: 1, location: 'rear', label: 'DC jack' },
      ],
      sources: ['ac'],
    },
    presentation: { faceplate: 'network', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-wifi-router',
    slug: 'wifi-router',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: 'Wireless Router',
    modelNumber: 'AC1200',
    category: 'routing',
    rackUnits: 1,
    widthMm: 231,
    heightMm: 35,
    depthMm: 147,
    mountingStandard: 'none',
    weightKg: 0.55,
    powerConsumptionWatts: 10,
    maximumPowerWatts: 15,
    description:
      'Dual-band AC wireless router with four external antennas, gigabit WAN and four-port LAN switch. Full-size desktop unit for shelf mounting.',
    tags: ['router', 'wifi', 'wireless', 'desktop', 'antenna'],
    // The shipped GLB is fully canonical: axis fix, full-size scale
    // (width -> 231 mm), LED face toward +Z and the antenna/port edge at
    // the rear are all baked into the asset's root matrix. The explicit
    // identity transform pins that in place — auto-derivation would
    // center the bounds (which include the tall antennas) and sink the
    // chassis through the shelf deck.
    modelTransform: {
      scale: 1,
      rotationDeg: [0, 0, 0],
      offsetMm: [0, 0, 0],
    },
    ports: [
      {
        id: 'wan',
        type: 'rj45',
        count: 1,
        label: 'WAN',
        location: 'rear',
        positionMm: [-51.5, -2, -73.5],
        speedGbps: 1,
      },
      {
        id: 'lan',
        type: 'rj45',
        count: 4,
        label: 'LAN',
        location: 'rear',
        positionMm: [-17, -2, -73.5],
        pitchMm: 23,
        speedGbps: 1,
      },
    ],
    power: {
      connectors: [
        {
          id: 'dc',
          type: 'dc',
          count: 1,
          location: 'rear',
          positionMm: [-77, -2, -73.5],
          label: 'DC jack',
        },
      ],
      sources: ['ac'],
    },
    presentation: { faceplate: 'network', tone: 'dark' },
  }),
];
