import { defineDevice } from './defineDevice';
import type { DeviceDefinition } from '../deviceSchema';

/**
 * Passive rail hardware: patch panels, blank and brush panels. Every
 * keystone opening is a real addressable connector location — future
 * cables terminate on the same stable refs as switch ports.
 */
export const GENERIC_DEVICES: DeviceDefinition[] = [
  defineDevice({
    id: 'gen-patch-24',
    slug: 'patch-panel-24',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '24-Port Keystone Panel',
    modelNumber: 'PP-24K',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 40,
    weightKg: 0.9,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Unloaded 1U keystone patch panel with 24 addressable openings.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone',
        type: 'keystone',
        count: 24,
        label: 'Keystone 1–24',
        positionMm: [-205.8, 0, 20],
        pitchMm: 17.9,
      },
    ],
    presentation: { faceplate: 'network', tone: 'dark', portsLabel: '24 openings' },
  }),
  defineDevice({
    id: 'gen-patch-48',
    slug: 'patch-panel-48',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '48-Port Keystone Panel',
    modelNumber: 'PP-48K',
    category: 'accessories',
    rackUnits: 2,
    depthMm: 40,
    weightKg: 1.7,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Unloaded 2U keystone patch panel with 48 addressable openings in two rows.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone-a',
        type: 'keystone',
        count: 24,
        label: 'Keystone 1–24',
        positionMm: [-205.8, 21, 20],
        pitchMm: 17.9,
        row: 0,
      },
      {
        id: 'keystone-b',
        type: 'keystone',
        count: 24,
        label: 'Keystone 25–48',
        positionMm: [-205.8, -21, 20],
        pitchMm: 17.9,
        row: 1,
      },
    ],
    presentation: { faceplate: 'network', tone: 'dark', portsLabel: '48 openings' },
  }),
  defineDevice({
    id: 'gen-blank-1u',
    slug: 'blank-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Blank Panel',
    modelNumber: 'BP-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 15,
    weightKg: 0.3,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Solid filler panel for unused rack units.',
    tags: ['blank', 'passive'],
    accessoryKind: 'blank-panel',
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-brush-1u',
    slug: 'brush-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Brush Panel',
    modelNumber: 'BR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 25,
    weightKg: 0.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Cable pass-through panel with a full-width brush strip.',
    tags: ['brush', 'cable-management', 'passive'],
    accessoryKind: 'brush-panel',
    cableManagement: {
      kind: 'brush-panel',
      capacity: 48,
      costFactor: 0.8,
      nodes: [
        // Cables pass front↔rear through the brush strip.
        { id: 'brush-l', positionMm: [-110, 0, 0], axisMm: [0, 0, 1] },
        { id: 'brush-c', positionMm: [0, 0, 0], axisMm: [0, 0, 1] },
        { id: 'brush-r', positionMm: [110, 0, 0], axisMm: [0, 0, 1] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-mgmt-1u',
    slug: 'cable-manager-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Horizontal Cable Manager',
    modelNumber: 'CM-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 70,
    weightKg: 0.7,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Open finger-style horizontal manager: patch cables sweep in from either side and dress across the front.',
    tags: ['cable-management', 'horizontal', 'finger', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'horizontal-manager',
      capacity: 24,
      costFactor: 0.6,
      nodes: [
        { id: 'run-l', positionMm: [-140, 0, 80], axisMm: [1, 0, 0] },
        { id: 'run-c', positionMm: [0, 0, 80], axisMm: [1, 0, 0] },
        { id: 'run-r', positionMm: [140, 0, 80], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-finger-duct-2u',
    slug: 'finger-duct-2u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '2U Finger Duct',
    modelNumber: 'FD-2U',
    category: 'accessories',
    rackUnits: 2,
    depthMm: 90,
    weightKg: 1.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'High-density covered finger duct for heavy patch fields; cables enter between the fingers and run enclosed.',
    tags: ['cable-management', 'finger-duct', 'horizontal', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'finger-duct',
      capacity: 48,
      costFactor: 0.5,
      enclosed: true,
      nodes: [
        { id: 'duct-l', positionMm: [-140, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
        { id: 'duct-c', positionMm: [0, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
        { id: 'duct-r', positionMm: [140, 0, 90], axisMm: [1, 0, 0], capacity: 24 },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-ring-1u',
    slug: 'cable-ring-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U D-Ring Guide',
    modelNumber: 'DR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 55,
    weightKg: 0.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Two steel D-rings for light patch-cable dressing.',
    tags: ['cable-management', 'ring', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'cable-ring',
      capacity: 12,
      costFactor: 0.85,
      nodes: [
        { id: 'ring-l', positionMm: [-110, 0, 70], axisMm: [1, 0, 0], capacity: 6 },
        { id: 'ring-r', positionMm: [110, 0, 70], axisMm: [1, 0, 0], capacity: 6 },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-vertical-mgmt-4u',
    slug: 'vertical-manager-4u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '4U Vertical Manager',
    modelNumber: 'VM-4U',
    category: 'accessories',
    rackUnits: 4,
    widthMm: 80,
    depthMm: 90,
    weightKg: 1.8,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Vertical finger spine beside the right rail: reserves its span and carries vertical runs between patch fields.',
    tags: ['cable-management', 'vertical', 'finger', 'passive'],
    accessoryKind: 'cable-manager',
    mountingOffsetMm: 262,
    cableManagement: {
      kind: 'vertical-manager',
      capacity: 48,
      costFactor: 0.55,
      nodes: [
        { id: 'v-top', positionMm: [0, 66, 80], axisMm: [0, 1, 0] },
        { id: 'v-mid', positionMm: [0, 0, 80], axisMm: [0, 1, 0] },
        { id: 'v-bottom', positionMm: [0, -66, 80], axisMm: [0, 1, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-cable-tray-1u',
    slug: 'cable-tray-rear-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Rear Cable Tray',
    modelNumber: 'CT-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 250,
    weightKg: 1.1,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Rear-mounted lattice tray carrying trunk runs across the back of the rack.',
    tags: ['cable-management', 'tray', 'rear', 'passive'],
    accessoryKind: 'cable-manager',
    defaultFacing: 'rear',
    cableManagement: {
      kind: 'cable-tray',
      capacity: 36,
      costFactor: 0.65,
      nodes: [
        { id: 'tray-l', positionMm: [-140, 0, -140], axisMm: [1, 0, 0] },
        { id: 'tray-c', positionMm: [0, 0, -140], axisMm: [1, 0, 0] },
        { id: 'tray-r', positionMm: [140, 0, -140], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'metal' },
  }),
  defineDevice({
    id: 'gen-power-raceway-1u',
    slug: 'power-raceway-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Power Raceway',
    modelNumber: 'PR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 250,
    weightKg: 1.2,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Dedicated rear raceway for power cords — keeps mains separated from data runs.',
    tags: ['cable-management', 'raceway', 'power', 'rear', 'passive'],
    accessoryKind: 'cable-manager',
    defaultFacing: 'rear',
    cableManagement: {
      kind: 'raceway',
      capacity: 16,
      costFactor: 0.6,
      enclosed: true,
      preferredFamilies: ['power'],
      nodes: [
        { id: 'race-l', positionMm: [-140, 0, -150], axisMm: [1, 0, 0] },
        { id: 'race-r', positionMm: [140, 0, -150], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-patch-guide-1u',
    slug: 'patch-guide-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Patch Cable Guide',
    modelNumber: 'PG-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 45,
    weightKg: 0.5,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Low-profile guide bar placed directly under a patch panel for short, tidy patch runs.',
    tags: ['cable-management', 'patch', 'guide', 'passive'],
    accessoryKind: 'cable-manager',
    cableManagement: {
      kind: 'patch-guide',
      capacity: 24,
      costFactor: 0.7,
      preferredFamilies: ['copper', 'fiber'],
      nodes: [
        { id: 'guide-c', positionMm: [0, 0, 65], axisMm: [1, 0, 0] },
      ],
    },
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
];
