import { defineDevice } from './defineDevice';
import type { DeviceDefinition } from '../deviceSchema';

/**
 * Passive rail hardware: patch panels, blank and brush panels. Every
 * keystone opening is a real addressable connector location — future
 * cables terminate on the same stable refs as switch ports.
 */
export const GENERIC_DEVICES: DeviceDefinition[] = [
  defineDevice({
    id: 'gen-patch-24',
    slug: 'patch-panel-24',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '24-Port Keystone Panel',
    modelNumber: 'PP-24K',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 40,
    weightKg: 0.9,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Unloaded 1U keystone patch panel with 24 addressable openings.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone',
        type: 'keystone',
        count: 24,
        label: 'Keystone 1–24',
        positionMm: [-205.8, 0, 20],
        pitchMm: 17.9,
      },
    ],
    presentation: { faceplate: 'network', tone: 'dark', portsLabel: '24 openings' },
  }),
  defineDevice({
    id: 'gen-patch-48',
    slug: 'patch-panel-48',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '48-Port Keystone Panel',
    modelNumber: 'PP-48K',
    category: 'accessories',
    rackUnits: 2,
    depthMm: 40,
    weightKg: 1.7,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description:
      'Unloaded 2U keystone patch panel with 48 addressable openings in two rows.',
    tags: ['patch-panel', 'keystone', 'passive'],
    accessoryKind: 'patch-panel',
    ports: [
      {
        id: 'keystone-a',
        type: 'keystone',
        count: 24,
        label: 'Keystone 1–24',
        positionMm: [-205.8, 21, 20],
        pitchMm: 17.9,
        row: 0,
      },
      {
        id: 'keystone-b',
        type: 'keystone',
        count: 24,
        label: 'Keystone 25–48',
        positionMm: [-205.8, -21, 20],
        pitchMm: 17.9,
        row: 1,
      },
    ],
    presentation: { faceplate: 'network', tone: 'dark', portsLabel: '48 openings' },
  }),
  defineDevice({
    id: 'gen-blank-1u',
    slug: 'blank-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Blank Panel',
    modelNumber: 'BP-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 15,
    weightKg: 0.3,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Solid filler panel for unused rack units.',
    tags: ['blank', 'passive'],
    accessoryKind: 'blank-panel',
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
  defineDevice({
    id: 'gen-brush-1u',
    slug: 'brush-panel-1u',
    manufacturer: 'generic',
    manufacturerName: 'Generic',
    productName: '1U Brush Panel',
    modelNumber: 'BR-1U',
    category: 'accessories',
    rackUnits: 1,
    depthMm: 25,
    weightKg: 0.4,
    powerConsumptionWatts: 0,
    maximumPowerWatts: 0,
    description: 'Cable pass-through panel with a full-width brush strip.',
    tags: ['brush', 'cable-management', 'passive'],
    accessoryKind: 'brush-panel',
    presentation: { faceplate: 'server', tone: 'dark' },
  }),
];
