import { defineDevice } from './defineDevice';
import type { DeviceDefinition } from '../deviceSchema';

export const UBIQUITI_DEVICES: DeviceDefinition[] = [
  defineDevice({
    id: 'ubnt-udm-pro',
    slug: 'dream-machine-pro',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Dream Machine Pro',
    modelNumber: 'UDM-Pro',
    category: 'routing',
    rackUnits: 1,
    depthMm: 286,
    weightKg: 3.9,
    powerConsumptionWatts: 33,
    maximumPowerWatts: 50,
    description:
      'All-in-one enterprise gateway with integrated switching, protect NVR and 10G uplinks.',
    tags: ['gateway', 'unifi', '10g', 'popular'],
    // The GLB is authored width-along-Z with its origin at the chassis
    // base; rotate -90° about Y and drop by half the height (see
    // public/devices/ubiquiti/dream-machine-pro/metadata.json).
    modelTransform: { rotationDeg: [0, -90, 0], offsetMm: [0, -22.5, 0] },
    ports: [
      { id: 'lan', type: 'rj45', count: 8, label: 'LAN 1–8', speedGbps: 1 },
      { id: 'wan', type: 'rj45', count: 1, label: 'WAN', speedGbps: 1 },
      { id: 'sfp-lan', type: 'sfp+', count: 1, label: 'SFP+ LAN', speedGbps: 10 },
      { id: 'sfp-wan', type: 'sfp+', count: 1, label: 'SFP+ WAN', speedGbps: 10 },
    ],
    leds: [{ id: 'status', label: 'Status ring', color: '#4c82f7' }],
    display: {
      lcd: true,
      positionMm: [178, 0, 143],
      widthMm: 33,
      heightMm: 33,
      resolution: [240, 240],
      bezelMm: 3,
    },
    power: {
      connectors: [{ id: 'ac', type: 'c14', count: 1, location: 'rear' }],
      sources: ['ac'],
    },
    cooling: { fanCount: 2, airflow: 'front-to-rear', fanDiameterMm: 40 },
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'popular',
      portsLabel: '10 ports',
      speedLabel: '10G SFP+',
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-48-poe',
    slug: 'usw-pro-48-poe',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro 48 PoE',
    modelNumber: 'USW-Pro-48-PoE',
    category: 'switching',
    rackUnits: 1,
    depthMm: 400,
    weightKg: 5.9,
    powerConsumptionWatts: 75,
    maximumPowerWatts: 600,
    description:
      'Layer 3 switch with 48 GbE PoE+ ports, four 10G SFP+ uplinks and quiet adaptive cooling.',
    tags: ['poe', 'layer3', 'popular'],
    ports: [
      { id: 'poe', type: 'rj45', count: 48, label: 'PoE+ 1–48' },
      { id: 'uplink', type: 'sfp+', count: 4, label: 'SFP+ uplinks' },
    ],
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'popular',
      portsLabel: '52 ports',
      speedLabel: '1G / 10G',
      poe: true,
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-max-24-poe',
    slug: 'pro-max-24-poe',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro Max 24 PoE',
    modelNumber: 'USW-Pro-Max-24-PoE',
    category: 'switching',
    rackUnits: 1,
    widthMm: 442,
    heightMm: 44,
    depthMm: 325,
    weightKg: 3.9,
    powerConsumptionWatts: 44,
    maximumPowerWatts: 444,
    // No modelTransform: the GLB is authored width-along-X with the
    // front toward +Z, so the universal importer derives the correction
    // (base-origin drop) automatically.
    description:
      'Etherlighting switch with 16 GbE and 8 2.5 GbE PoE ports, dual 10G SFP+ uplinks and a 400 W PoE budget.',
    tags: ['poe', 'etherlighting', '2.5g', '10g', 'new'],
    ports: [
      // 24 RJ45 in two rows of 12 (odd top, even bottom), like the
      // physical switch: 1G ports 1–16, 2.5G ports 17–24.
      {
        id: 'gbe-top',
        type: 'rj45',
        count: 8,
        label: '1 GbE PoE (top row)',
        positionMm: [-158, 7.5, 162.5],
        pitchMm: 17.9,
        row: 0,
        speedGbps: 1,
        poe: true,
        etherlighting: true,
      },
      {
        id: 'gbe-bottom',
        type: 'rj45',
        count: 8,
        label: '1 GbE PoE (bottom row)',
        positionMm: [-158, -7.5, 162.5],
        pitchMm: 17.9,
        row: 1,
        speedGbps: 1,
        poe: true,
        etherlighting: true,
      },
      {
        id: '2p5gbe-top',
        type: 'rj45',
        count: 4,
        label: '2.5 GbE PoE (top row)',
        positionMm: [-8, 7.5, 162.5],
        pitchMm: 17.9,
        row: 0,
        speedGbps: 2.5,
        poe: true,
        etherlighting: true,
      },
      {
        id: '2p5gbe-bottom',
        type: 'rj45',
        count: 4,
        label: '2.5 GbE PoE (bottom row)',
        positionMm: [-8, -7.5, 162.5],
        pitchMm: 17.9,
        row: 1,
        speedGbps: 2.5,
        poe: true,
        etherlighting: true,
      },
      {
        id: 'sfp',
        type: 'sfp+',
        count: 2,
        label: 'SFP+ 25–26',
        positionMm: [86, 7.5, 162.5],
        pitchMm: 18.5,
        speedGbps: 10,
      },
    ],
    power: {
      connectors: [{ id: 'ac', type: 'c14', count: 1, location: 'rear' }],
      poeBudgetW: 400,
      sources: ['ac'],
    },
    cooling: { fanCount: 2, airflow: 'side-to-side', fanDiameterMm: 40 },
    leds: [
      {
        id: 'status',
        label: 'System status',
        kind: 'status',
        color: '#4c82f7',
        positionMm: [205, 8, 162.5],
      },
    ],
    lighting: {
      etherlighting: true,
      perPortLink: true,
      poeIndicator: true,
      speedColors: { '1g': '#9aa3ad', '2.5g': '#22c1a4', '10g': '#7c5cff' },
      portHighlightColor: '#4c82f7',
      statusLed: { color: '#4c82f7', positionMm: [205, 8, 162.5] },
      effects: ['breathe', 'rainbow'],
    },
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'new',
      portsLabel: '26 ports',
      speedLabel: '2.5G / 10G',
      poe: true,
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-aggregation',
    slug: 'usw-pro-aggregation',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro Aggregation',
    modelNumber: 'USW-Pro-Aggregation',
    category: 'switching',
    rackUnits: 1,
    depthMm: 296,
    weightKg: 3.6,
    powerConsumptionWatts: 60,
    maximumPowerWatts: 85,
    description:
      'Aggregation switch with 28 SFP+ and four SFP28 ports for high-capacity cores.',
    tags: ['aggregation', '10g', '25g'],
    ports: [
      { id: 'sfp10-top', type: 'sfp+', count: 14, label: 'SFP+ (top row)', row: 0, speedGbps: 10 },
      { id: 'sfp10-bottom', type: 'sfp+', count: 14, label: 'SFP+ (bottom row)', row: 1, speedGbps: 10 },
      { id: 'sfp25', type: 'sfp28', count: 4, label: 'SFP28 uplinks', row: 0, speedGbps: 25 },
    ],
    power: {
      connectors: [{ id: 'ac', type: 'c14', count: 1, location: 'rear' }],
      sources: ['ac'],
    },
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      portsLabel: '32 ports',
      speedLabel: '10G / 25G',
    },
  }),
  defineDevice({
    id: 'ubnt-unvr-pro',
    slug: 'unvr-pro',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'UNVR Pro',
    modelNumber: 'UNVR-Pro',
    category: 'storage',
    rackUnits: 2,
    depthMm: 480,
    weightKg: 12.6,
    powerConsumptionWatts: 210,
    maximumPowerWatts: 250,
    description:
      'Network video recorder with seven hot-swap bays for around-the-clock camera retention.',
    tags: ['nvr', 'protect', '10g'],
    ports: [
      { id: 'mgmt', type: 'rj45', count: 1, label: 'Management', speedGbps: 1 },
      { id: 'sfp', type: 'sfp+', count: 2, label: 'SFP+', speedGbps: 10 },
    ],
    display: {
      lcd: true,
      positionMm: [175, 0, 240],
      widthMm: 38,
      heightMm: 24,
      resolution: [320, 200],
      bezelMm: 3,
    },
    power: {
      connectors: [
        { id: 'psu', type: 'c14', count: 2, location: 'rear', label: 'Redundant PSU' },
      ],
      redundant: true,
      hotSwappable: true,
      psuCount: 2,
      sources: ['ac'],
    },
    cooling: {
      fanCount: 2,
      airflow: 'front-to-rear',
      fanDiameterMm: 60,
      fanPositionsMm: [
        [-100, 0, -240],
        [100, 0, -240],
      ],
      intake: ['front'],
      exhaust: ['rear'],
    },
    presentation: {
      faceplate: 'storage',
      tone: 'dark',
      portsLabel: '2 ports',
      speedLabel: '10G SFP+',
    },
  }),
];
