import { defineDevice } from './defineDevice';
import type { DeviceDefinition } from '../deviceSchema';

export const UBIQUITI_DEVICES: DeviceDefinition[] = [
  defineDevice({
    id: 'ubnt-udm-pro',
    slug: 'dream-machine-pro',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Dream Machine Pro',
    modelNumber: 'UDM-Pro',
    category: 'routing',
    rackUnits: 1,
    depthMm: 286,
    weightKg: 3.9,
    powerConsumptionWatts: 33,
    maximumPowerWatts: 50,
    description:
      'All-in-one enterprise gateway with integrated switching, protect NVR and 10G uplinks.',
    tags: ['gateway', 'unifi', '10g', 'popular'],
    // The GLB is authored width-along-Z with its origin at the chassis
    // base; rotate -90° about Y and drop by half the height (see
    // public/devices/ubiquiti/dream-machine-pro/metadata.json).
    modelTransform: { rotationDeg: [0, -90, 0], offsetMm: [0, -22.5, 0] },
    ports: [
      { id: 'lan', type: 'rj45', count: 8, label: 'LAN 1–8' },
      { id: 'wan', type: 'rj45', count: 1, label: 'WAN' },
      { id: 'sfp-lan', type: 'sfp+', count: 1, label: 'SFP+ LAN' },
      { id: 'sfp-wan', type: 'sfp+', count: 1, label: 'SFP+ WAN' },
    ],
    leds: [{ id: 'status', label: 'Status ring', color: '#4c82f7' }],
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'popular',
      portsLabel: '10 ports',
      speedLabel: '10G SFP+',
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-48-poe',
    slug: 'usw-pro-48-poe',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro 48 PoE',
    modelNumber: 'USW-Pro-48-PoE',
    category: 'switching',
    rackUnits: 1,
    depthMm: 400,
    weightKg: 5.9,
    powerConsumptionWatts: 75,
    maximumPowerWatts: 600,
    description:
      'Layer 3 switch with 48 GbE PoE+ ports, four 10G SFP+ uplinks and quiet adaptive cooling.',
    tags: ['poe', 'layer3', 'popular'],
    ports: [
      { id: 'poe', type: 'rj45', count: 48, label: 'PoE+ 1–48' },
      { id: 'uplink', type: 'sfp+', count: 4, label: 'SFP+ uplinks' },
    ],
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'popular',
      portsLabel: '52 ports',
      speedLabel: '1G / 10G',
      poe: true,
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-max-24-poe',
    slug: 'pro-max-24-poe',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro Max 24 PoE',
    modelNumber: 'USW-Pro-Max-24-PoE',
    category: 'switching',
    rackUnits: 1,
    widthMm: 442,
    heightMm: 44,
    depthMm: 325,
    weightKg: 3.9,
    powerConsumptionWatts: 44,
    maximumPowerWatts: 444,
    // GLB is authored width-along-X, front toward +Z, base at the origin:
    // only the half-height drop is needed.
    modelTransform: { offsetMm: [0, -21.85, 0] },
    description:
      'Etherlighting switch with 16 GbE and 8 2.5 GbE PoE ports, dual 10G SFP+ uplinks and a 400 W PoE budget.',
    tags: ['poe', 'etherlighting', '2.5g', '10g', 'new'],
    ports: [
      {
        id: 'gbe',
        type: 'rj45',
        count: 16,
        label: '1 GbE PoE 1–16',
        positionMm: [-140, 0, 162.5],
        pitchMm: 17.9,
        speedGbps: 1,
        poe: true,
        etherlighting: true,
      },
      {
        id: '2p5gbe',
        type: 'rj45',
        count: 8,
        label: '2.5 GbE PoE 17–24',
        positionMm: [4, 0, 162.5],
        pitchMm: 17.9,
        speedGbps: 2.5,
        poe: true,
        etherlighting: true,
      },
      {
        id: 'sfp',
        type: 'sfp+',
        count: 2,
        label: 'SFP+ 25–26',
        positionMm: [160, 0, 162.5],
        pitchMm: 18.5,
        speedGbps: 10,
      },
    ],
    leds: [
      {
        id: 'status',
        label: 'System status',
        kind: 'status',
        color: '#4c82f7',
        positionMm: [205, 8, 162.5],
      },
    ],
    lighting: {
      etherlighting: true,
      perPortLink: true,
      poeIndicator: true,
      speedColors: { '1g': '#9aa3ad', '2.5g': '#22c1a4', '10g': '#7c5cff' },
      portHighlightColor: '#4c82f7',
      statusLed: { color: '#4c82f7', positionMm: [205, 8, 162.5] },
      effects: ['breathe', 'rainbow'],
    },
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      badge: 'new',
      portsLabel: '26 ports',
      speedLabel: '2.5G / 10G',
      poe: true,
    },
  }),
  defineDevice({
    id: 'ubnt-usw-pro-aggregation',
    slug: 'usw-pro-aggregation',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'Pro Aggregation',
    modelNumber: 'USW-Pro-Aggregation',
    category: 'switching',
    rackUnits: 1,
    depthMm: 296,
    weightKg: 3.6,
    powerConsumptionWatts: 60,
    maximumPowerWatts: 85,
    description:
      'Aggregation switch with 28 SFP+ and four SFP28 ports for high-capacity cores.',
    tags: ['aggregation', '10g', '25g'],
    ports: [
      { id: 'sfp10', type: 'sfp+', count: 28, label: 'SFP+ 1–28' },
      { id: 'sfp25', type: 'sfp28', count: 4, label: 'SFP28 uplinks' },
    ],
    presentation: {
      faceplate: 'network',
      tone: 'dark',
      portsLabel: '32 ports',
      speedLabel: '10G / 25G',
    },
  }),
  defineDevice({
    id: 'ubnt-unvr-pro',
    slug: 'unvr-pro',
    manufacturer: 'ubiquiti',
    manufacturerName: 'Ubiquiti',
    productName: 'UNVR Pro',
    modelNumber: 'UNVR-Pro',
    category: 'storage',
    rackUnits: 2,
    depthMm: 480,
    weightKg: 12.6,
    powerConsumptionWatts: 210,
    maximumPowerWatts: 250,
    description:
      'Network video recorder with seven hot-swap bays for around-the-clock camera retention.',
    tags: ['nvr', 'protect', '10g'],
    ports: [{ id: 'sfp', type: 'sfp+', count: 2, label: 'SFP+' }],
    presentation: {
      faceplate: 'storage',
      tone: 'dark',
      portsLabel: '2 ports',
      speedLabel: '10G SFP+',
    },
  }),
];
